name: "Build Image for testing purposes (amd64 only)"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  # we only test if a build passes on amd64 (faster)
  PLATFORMS: linux/amd64

jobs:
  build_fpm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "8.4"
          - php-version: "8.3"
          - php-version: "8.2"
          - php-version: "8.1"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: "Docker build only (fpm image)"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: "croneu/phpapp-fpm:php-${{ matrix.php-version }}"
          platforms: ${{ env.PLATFORMS }}
          push: false
          cache-from: type=gha,scope=php-${{ matrix.php-version }}-${{ env.PLATFORMS }}
          cache-to: type=gha,mode=max,scope=php-${{ matrix.php-version }}-${{ env.PLATFORMS }}
          target: php-fpm
          build-args: |
            PHP_MINOR_VERSION=${{ matrix.php-version }}

  build_ssh:
    needs:
      - build_fpm

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "8.4"
            node-version: "22"
          - php-version: "8.3"
            node-version: "20"
          - php-version: "8.2"
            node-version: "18"
          - php-version: "8.1"
            node-version: "16"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: "Docker build only (ssh image)"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: "croneu/phpapp-ssh:php-${{ matrix.php-version }}-node-${{ matrix.node-version }}"
          platforms: ${{ env.PLATFORMS }}
          push: false
          cache-from: type=gha,scope=php-${{ matrix.php-version }}-node-${{ matrix.node-version }}-${{ env.PLATFORMS }}
          cache-to: type=gha,mode=max,scope=php-${{ matrix.php-version }}-node-${{ matrix.node-version }}-${{ env.PLATFORMS }}
          target: ssh
          build-args: |
            PHP_MINOR_VERSION=${{ matrix.php-version }}
            NODE_VERSION=${{ matrix.node-version }}
