name: "Build Image for testing purposes (amd64 only)"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  # we only test if a build passes on amd64 (faster)
  PLATFORMS: linux/amd64

jobs:
  build_fpm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "8.2"
          - php-version: "8.1"
          - php-version: "7.4"
          - php-version: "7.3"
          - php-version: "7.2"
          - php-version: "7.0"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v2

      - name: "Docker build only (fpm image)"
        uses: docker/build-push-action@v4
        with:
          tags: "croneu/phpapp-fpm:php-${{ matrix.php-version }}"
          platforms: ${{ env.PLATFORMS }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: php-fpm
          build-args: |
            PHP_MINOR_VERSION=${{ matrix.php-version }}

  build_ssh:
    needs:
      - build_fpm

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "8.2"
            node-version: "18"
          - php-version: "8.1"
            node-version: "16"
          - php-version: "7.4"
            node-version: "16"
          - php-version: "7.3"
            node-version: "10"
          - php-version: "7.2"
            node-version: "10"
          - php-version: "7.0"
            node-version: "14"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v2

      - name: "Docker build and push (ssh image)"
        uses: docker/build-push-action@v4
        with:
          tags: "croneu/phpapp-ssh:php-${{ matrix.php-version }}-node-${{ matrix.node-version }}"
          platforms: ${{ env.PLATFORMS }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ssh
          build-args: |
            PHP_MINOR_VERSION=${{ matrix.php-version }}
            NODE_VERSION=${{ matrix.node-version }}
