name: "Build Image for testing purposes (amd64 only)"

on:
  pull_request:
    branches:
      - master

jobs:
  build_fpm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "7.4"
          - php-version: "7.3"
          - php-version: "7.2"
          - php-version: "7.0"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v1

      - name: "Cache Docker layers"
        uses: actions/cache@v2
        with:
          path: .buildx-cache
          key: buildx-${{ matrix.php-version }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.php-version }}-${{ github.sha }}
            buildx-${{ matrix.php-version }}
            buildx

      - name: "Docker build php-${{ matrix.php-version }}"
        run: |
          make build-fpm PHP_VERSION=${{ matrix.php-version }} \
            PLATFORMS=linux/amd64 DOCKER_CACHE_PATH=.buildx-cache

      - name: "Upload artefacts for our next job to use"
        uses: actions/upload-artifact@v2
        with:
          name: buildx-${{ matrix.php-version }}-${{ github.sha }}
          path: .buildx-cache

  build_ssh:
    needs:
      - build_fpm

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "7.4"
            node-version: "16"
          - php-version: "7.4"
            node-version: "14"
          - php-version: "7.4"
            node-version: "12"
          - php-version: "7.4"
            node-version: "10"
          - php-version: "7.3"
            node-version: "10"
          - php-version: "7.2"
            node-version: "10"
          - php-version: "7.0"
            node-version: "10"

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v1

      - name: "Download already created docker layers"
        uses: actions/download-artifact@v2
        with:
          name: buildx-${{ matrix.php-version }}-${{ github.sha }}
          path: .buildx-cache

      - name: "Docker build php-${{ matrix.php-version }} node-${{ matrix.node-version }}"
        run: |
          make build-ssh PHP_VERSION=${{ matrix.php-version }} NODE_VERSION=${{ matrix.node-version }} \
            PLATFORMS=linux/amd64 DOCKER_CACHE_PATH=.buildx-cache
